export const DEFAULT_ROLES_200: string[] = [
  "Project Manager",
  "Data Analyst",
  "Data Engineer",
  "RPA Developer",
  "QA Engineer",
  "AI Engineer",
  "Cuidadora de Adultos Mayores",
  "Auxiliar de Enfermería",
  "UX Designer",
  "UI Designer",
  "Desarrollador React",
  "Desarrollador Node.js",
  "Desarrollador Python",
  "Desarrollador Java",
  "Desarrollador Full Stack",
  "Desarrollador Frontend",
  "Desarrollador Backend",
  "Desarrollador Mobile",
  "Ingeniero DevOps",
  "Ingeniero Civil",
  "Ingeniero Ambiental",
  "Arquitecto de Software",
  "Scrum Master",
  "Product Owner",
  "Business Analyst",
  "Diseñador Gráfico",
  "Community Manager",
  "Especialista en Marketing Digital",
  "Contador Público",
  "Auxiliar Administrativo",
  "Ejecutivo de Ventas",
  "Asesor Comercial"
];
